export interface CarrierSeed {
  name: string;
  ticker: string | null;
  exchange: string | null;
  headquartersCountry: string;
  companyType: string;
  linesOfBusiness: string;
  isPubliclyTraded: boolean;
  description: string;
  website: string | null;
  cikNumber: string | null;
  category: string;
  parentCompany: string | null;
}

export const carriers: CarrierSeed[] = [
  // ──────────────────────────────────────────────
  // Large-Cap US P&C Carriers
  // ──────────────────────────────────────────────
  {
    name: "Chubb Limited",
    ticker: "CB",
    exchange: "NYSE",
    headquartersCountry: "Switzerland",
    companyType: "primary_carrier",
    linesOfBusiness: JSON.stringify(["Commercial P&C", "Personal Lines", "Specialty", "Reinsurance", "Life"]),
    isPubliclyTraded: true,
    description: "World's largest publicly traded P&C insurer. Operates in 54 countries with a diversified portfolio spanning commercial, personal, specialty, and reinsurance lines.",
    website: "https://www.chubb.com",
    cikNumber: "0000896159",
    category: "us_pc",
    parentCompany: null,
  },
  {
    name: "Progressive Corporation",
    ticker: "PGR",
    exchange: "NYSE",
    headquartersCountry: "United States",
    companyType: "primary_carrier",
    linesOfBusiness: JSON.stringify(["Personal Auto", "Commercial Auto", "Property", "Specialty"]),
    isPubliclyTraded: true,
    description: "Third-largest US auto insurer. Pioneer in usage-based insurance (Snapshot). Known for direct-to-consumer model and disciplined pricing through data analytics.",
    website: "https://www.progressive.com",
    cikNumber: "0000080661",
    category: "us_pc",
    parentCompany: null,
  },
  {
    name: "Allstate Corporation",
    ticker: "ALL",
    exchange: "NYSE",
    headquartersCountry: "United States",
    companyType: "primary_carrier",
    linesOfBusiness: JSON.stringify(["Personal Auto", "Homeowners", "Commercial Lines", "Protection Plans"]),
    isPubliclyTraded: true,
    description: "Second-largest personal lines insurer in the US. Major auto and homeowners carrier with growing protection plans and commercial lines segments.",
    website: "https://www.allstate.com",
    cikNumber: "0000899051",
    category: "us_pc",
    parentCompany: null,
  },
  {
    name: "American International Group (AIG)",
    ticker: "AIG",
    exchange: "NYSE",
    headquartersCountry: "United States",
    companyType: "primary_carrier",
    linesOfBusiness: JSON.stringify(["Commercial Lines", "Personal Insurance", "General Insurance", "Life & Retirement"]),
    isPubliclyTraded: true,
    description: "Global insurance organization providing commercial and personal insurance solutions. Recently spun off life & retirement business as Corebridge Financial.",
    website: "https://www.aig.com",
    cikNumber: "0000005272",
    category: "us_pc",
    parentCompany: null,
  },
  {
    name: "Travelers Companies",
    ticker: "TRV",
    exchange: "NYSE",
    headquartersCountry: "United States",
    companyType: "primary_carrier",
    linesOfBusiness: JSON.stringify(["Business Insurance", "Bond & Specialty Insurance", "Personal Insurance"]),
    isPubliclyTraded: true,
    description: "Leading US P&C insurer and Dow Jones Industrial Average component. Strong in commercial lines, workers' comp, and personal auto/homeowners.",
    website: "https://www.travelers.com",
    cikNumber: "0000086312",
    category: "us_pc",
    parentCompany: null,
  },
  {
    name: "The Hartford Financial Services",
    ticker: "HIG",
    exchange: "NYSE",
    headquartersCountry: "United States",
    companyType: "primary_carrier",
    linesOfBusiness: JSON.stringify(["Commercial Lines", "Personal Lines", "Group Benefits", "Hartford Funds"]),
    isPubliclyTraded: true,
    description: "Major US insurer focused on small and mid-size commercial lines, personal auto, homeowners, and group disability/life benefits.",
    website: "https://www.thehartford.com",
    cikNumber: "0000874766",
    category: "us_pc",
    parentCompany: null,
  },
  {
    name: "American Financial Group",
    ticker: "AFG",
    exchange: "NYSE",
    headquartersCountry: "United States",
    companyType: "primary_carrier",
    linesOfBusiness: JSON.stringify(["Specialty Casualty", "Specialty Financial", "Property & Transportation"]),
    isPubliclyTraded: true,
    description: "Specialty P&C insurer operating through Great American Insurance Group. Focused on niche commercial markets with strong underwriting discipline.",
    website: "https://www.afginc.com",
    cikNumber: "0001042046",
    category: "us_pc",
    parentCompany: null,
  },
  {
    name: "Assurant Inc",
    ticker: "AIZ",
    exchange: "NYSE",
    headquartersCountry: "United States",
    companyType: "primary_carrier",
    linesOfBusiness: JSON.stringify(["Specialty Property", "Connected Living", "Auto Solutions", "Renters"]),
    isPubliclyTraded: true,
    description: "Global provider of specialty protection products and services including mobile device protection, vehicle protection, and renters insurance.",
    website: "https://www.assurant.com",
    cikNumber: "0001267238",
    category: "us_pc",
    parentCompany: null,
  },
  // ──────────────────────────────────────────────
  // Mid-Cap & Specialty US P&C Carriers
  // ──────────────────────────────────────────────
  {
    name: "Markel Group",
    ticker: "MKL",
    exchange: "NYSE",
    headquartersCountry: "United States",
    companyType: "primary_carrier",
    linesOfBusiness: JSON.stringify(["Specialty Insurance", "E&S Lines", "Reinsurance", "Markel Ventures"]),
    isPubliclyTraded: true,
    description: "Diversified financial holding company focused on specialty insurance and E&S markets. Often compared to Berkshire Hathaway for its insurance + investment model.",
    website: "https://www.markel.com",
    cikNumber: "0001096343",
    category: "us_pc",
    parentCompany: null,
  },
  {
    name: "W.R. Berkley Corporation",
    ticker: "WRB",
    exchange: "NYSE",
    headquartersCountry: "United States",
    companyType: "primary_carrier",
    linesOfBusiness: JSON.stringify(["Commercial Lines", "Specialty Lines", "Reinsurance", "International"]),
    isPubliclyTraded: true,
    description: "Decentralized specialty commercial lines insurer operating through 50+ companies. Known for underwriting discipline and niche market expertise.",
    website: "https://www.berkley.com",
    cikNumber: "0000011544",
    category: "us_pc",
    parentCompany: null,
  },
  {
    name: "CNA Financial Corporation",
    ticker: "CNA",
    exchange: "NYSE",
    headquartersCountry: "United States",
    companyType: "primary_carrier",
    linesOfBusiness: JSON.stringify(["Commercial", "Specialty", "International", "Surety"]),
    isPubliclyTraded: true,
    description: "One of the largest US commercial property and casualty companies. Majority-owned by Loews Corporation. Strong in professional liability and management liability.",
    website: "https://www.cna.com",
    cikNumber: "0000021175",
    category: "us_pc",
    parentCompany: "Loews Corporation",
  },
  {
    name: "Kinsale Capital Group",
    ticker: "KNSL",
    exchange: "NASDAQ",
    headquartersCountry: "United States",
    companyType: "primary_carrier",
    linesOfBusiness: JSON.stringify(["E&S Casualty", "E&S Property", "Specialty"]),
    isPubliclyTraded: true,
    description: "Pure-play E&S insurer with technology-driven underwriting. Known for low expense ratios and focused specialty approach across small-account E&S business.",
    website: "https://www.kinsalecapitalgroup.com",
    cikNumber: "0001669162",
    category: "us_pc",
    parentCompany: null,
  },
  {
    name: "Kemper Corporation",
    ticker: "KMPR",
    exchange: "NYSE",
    headquartersCountry: "United States",
    companyType: "primary_carrier",
    linesOfBusiness: JSON.stringify(["Specialty Auto", "Preferred Auto", "Life Insurance"]),
    isPubliclyTraded: true,
    description: "Specialty personal lines insurer focused on non-standard and preferred auto insurance. Also operates life insurance and commercial auto segments.",
    website: "https://www.kemper.com",
    cikNumber: "0000860748",
    category: "us_pc",
    parentCompany: null,
  },
  // ──────────────────────────────────────────────
  // Regional US P&C Carriers
  // ──────────────────────────────────────────────
  {
    name: "Hanover Insurance Group",
    ticker: "THG",
    exchange: "NYSE",
    headquartersCountry: "United States",
    companyType: "primary_carrier",
    linesOfBusiness: JSON.stringify(["Commercial Lines", "Personal Lines", "Specialty"]),
    isPubliclyTraded: true,
    description: "Regional P&C insurer distributing through independent agents. Focused on small and mid-size commercial and personal lines across the US.",
    website: "https://www.hanover.com",
    cikNumber: "0000944695",
    category: "us_pc",
    parentCompany: null,
  },
  {
    name: "RLI Corp",
    ticker: "RLI",
    exchange: "NYSE",
    headquartersCountry: "United States",
    companyType: "primary_carrier",
    linesOfBusiness: JSON.stringify(["Casualty", "Property", "Surety"]),
    isPubliclyTraded: true,
    description: "Specialty insurer with exceptional underwriting track record. Focuses on niche casualty, property, and surety markets with consistently low combined ratios.",
    website: "https://www.rlicorp.com",
    cikNumber: "0000084246",
    category: "us_pc",
    parentCompany: null,
  },
  {
    name: "Cincinnati Financial Corporation",
    ticker: "CINF",
    exchange: "NASDAQ",
    headquartersCountry: "United States",
    companyType: "primary_carrier",
    linesOfBusiness: JSON.stringify(["Commercial Lines", "Personal Lines", "Excess & Surplus", "Life Insurance"]),
    isPubliclyTraded: true,
    description: "Independent agency-focused P&C insurer known for long-term agent relationships and consistent dividend growth. Operates primarily in the Midwest and Southeast.",
    website: "https://www.cinfin.com",
    cikNumber: "0000020286",
    category: "us_pc",
    parentCompany: null,
  },
  {
    name: "Erie Indemnity Company",
    ticker: "ERIE",
    exchange: "NASDAQ",
    headquartersCountry: "United States",
    companyType: "primary_carrier",
    linesOfBusiness: JSON.stringify(["Personal Auto", "Homeowners", "Commercial Multi-Peril", "Workers Comp"]),
    isPubliclyTraded: true,
    description: "Management company for the Erie Insurance Exchange. Top-rated for customer satisfaction in personal auto and homeowners. Operates in 12 mid-Atlantic and Midwest states.",
    website: "https://www.erieinsurance.com",
    cikNumber: "0000922621",
    category: "us_pc",
    parentCompany: null,
  },
  {
    name: "Donegal Group",
    ticker: "DGICA",
    exchange: "NASDAQ",
    headquartersCountry: "United States",
    companyType: "primary_carrier",
    linesOfBusiness: JSON.stringify(["Personal Lines", "Commercial Lines"]),
    isPubliclyTraded: true,
    description: "Regional P&C insurer operating through independent agents primarily in the Mid-Atlantic and Southeastern states. Subsidiary of Donegal Mutual Insurance Company.",
    website: "https://www.donegalgroup.com",
    cikNumber: "0000800457",
    category: "us_pc",
    parentCompany: "Donegal Mutual Insurance Company",
  },
  {
    name: "Horace Mann Educators Corporation",
    ticker: "HMN",
    exchange: "NYSE",
    headquartersCountry: "United States",
    companyType: "primary_carrier",
    linesOfBusiness: JSON.stringify(["Auto", "Homeowners", "Life", "Retirement"]),
    isPubliclyTraded: true,
    description: "Insurance company specializing in serving educators and school employees. Offers auto, property, life, and retirement products exclusively to the education market.",
    website: "https://www.horacemann.com",
    cikNumber: "0000850141",
    category: "us_pc",
    parentCompany: null,
  },
  // ──────────────────────────────────────────────
  // Cat-Exposed / Specialty Property Carriers
  // ──────────────────────────────────────────────
  {
    name: "Palomar Holdings",
    ticker: "PLMR",
    exchange: "NASDAQ",
    headquartersCountry: "United States",
    companyType: "primary_carrier",
    linesOfBusiness: JSON.stringify(["Earthquake", "Specialty Property", "Crop", "Fronting"]),
    isPubliclyTraded: true,
    description: "Specialty insurer focused on earthquake, Hawaiian hurricane, and other niche property risks. Asset-light model using reinsurance for capital efficiency.",
    website: "https://www.palomarspecialty.com",
    cikNumber: "0001761312",
    category: "us_pc",
    parentCompany: null,
  },
  {
    name: "HCI Group",
    ticker: "HCI",
    exchange: "NYSE",
    headquartersCountry: "United States",
    companyType: "primary_carrier",
    linesOfBusiness: JSON.stringify(["Homeowners", "Wind", "Flood", "Real Estate"]),
    isPubliclyTraded: true,
    description: "Florida-focused property insurer specializing in homeowners and wind coverage. Also operates real estate and information technology subsidiaries.",
    website: "https://www.hcigroup.com",
    cikNumber: "0001400810",
    category: "us_pc",
    parentCompany: null,
  },
  {
    name: "Heritage Insurance Holdings",
    ticker: "HRTG",
    exchange: "NYSE",
    headquartersCountry: "United States",
    companyType: "primary_carrier",
    linesOfBusiness: JSON.stringify(["Homeowners", "Commercial Residential", "Wind"]),
    isPubliclyTraded: true,
    description: "Property insurer focused on residential coverage in catastrophe-exposed states including Florida, Hawaii, and the Southeast.",
    website: "https://www.heritagepci.com",
    cikNumber: "0001598665",
    category: "us_pc",
    parentCompany: null,
  },
  {
    name: "Universal Insurance Holdings",
    ticker: "UVE",
    exchange: "NYSE",
    headquartersCountry: "United States",
    companyType: "primary_carrier",
    linesOfBusiness: JSON.stringify(["Homeowners", "Commercial Residential", "Wind"]),
    isPubliclyTraded: true,
    description: "Florida-domiciled property insurer and holding company providing homeowners insurance primarily in coastal and catastrophe-exposed markets.",
    website: "https://www.universalinsuranceholdings.com",
    cikNumber: "0000891166",
    category: "us_pc",
    parentCompany: null,
  },
  // ──────────────────────────────────────────────
  // Niche / Workers' Comp / Specialty
  // ──────────────────────────────────────────────
  {
    name: "Employers Holdings",
    ticker: "EIG",
    exchange: "NYSE",
    headquartersCountry: "United States",
    companyType: "primary_carrier",
    linesOfBusiness: JSON.stringify(["Workers Compensation"]),
    isPubliclyTraded: true,
    description: "Specialty workers' compensation insurer serving small to mid-size businesses in low-to-medium hazard industries across the US.",
    website: "https://www.employers.com",
    cikNumber: "0001379041",
    category: "us_pc",
    parentCompany: null,
  },
  {
    name: "Global Indemnity Group",
    ticker: "GBLI",
    exchange: "NASDAQ",
    headquartersCountry: "United States",
    companyType: "primary_carrier",
    linesOfBusiness: JSON.stringify(["Commercial Lines", "Specialty", "Farm & Ranch", "E&S"]),
    isPubliclyTraded: true,
    description: "Specialty P&C insurer offering commercial and personal lines including farm, ranch, and specialty property programs through managing general agents.",
    website: "https://www.globalindemnity.com",
    cikNumber: "0001494904",
    category: "us_pc",
    parentCompany: null,
  },
  {
    name: "Ally Financial",
    ticker: "ALLY",
    exchange: "NYSE",
    headquartersCountry: "United States",
    companyType: "primary_carrier",
    linesOfBusiness: JSON.stringify(["Dealer Financial Products", "Vehicle Service Contracts", "GAP Insurance", "Commercial Auto"]),
    isPubliclyTraded: true,
    description: "Leading auto finance company with insurance operations through Motors Insurance Corp. Provides dealer-centric financial products including F&I, VSCs, and GAP coverage.",
    website: "https://www.ally.com",
    cikNumber: "0000040729",
    category: "us_pc",
    parentCompany: null,
  },
  // ──────────────────────────────────────────────
  // Bermuda-Based Reinsurers (SEC Filers)
  // ──────────────────────────────────────────────
  {
    name: "Everest Group",
    ticker: "EG",
    exchange: "NYSE",
    headquartersCountry: "Bermuda",
    companyType: "reinsurer",
    linesOfBusiness: JSON.stringify(["P&C Reinsurance", "Insurance", "Specialty"]),
    isPubliclyTraded: true,
    description: "Leading global reinsurer and insurer operating through Everest Re and Everest Insurance. Active across treaty, facultative, and specialty lines.",
    website: "https://www.everestglobal.com",
    cikNumber: "0001095073",
    category: "reinsurer",
    parentCompany: null,
  },
  {
    name: "RenaissanceRe Holdings",
    ticker: "RNR",
    exchange: "NYSE",
    headquartersCountry: "Bermuda",
    companyType: "reinsurer",
    linesOfBusiness: JSON.stringify(["Property Cat Reinsurance", "Casualty Reinsurance", "Specialty Reinsurance"]),
    isPubliclyTraded: true,
    description: "Leading property catastrophe reinsurer known for sophisticated risk modeling and disciplined cycle management. Expanded casualty book significantly in recent years.",
    website: "https://www.renre.com",
    cikNumber: "0000913144",
    category: "reinsurer",
    parentCompany: null,
  },
  {
    name: "Arch Capital Group",
    ticker: "ACGL",
    exchange: "NASDAQ",
    headquartersCountry: "Bermuda",
    companyType: "reinsurer",
    linesOfBusiness: JSON.stringify(["Reinsurance", "Insurance", "Mortgage Insurance"]),
    isPubliclyTraded: true,
    description: "Bermuda-based insurer/reinsurer with strong track record. Operates across reinsurance, insurance, and mortgage guarantee segments. Known for disciplined underwriting.",
    website: "https://www.archgroup.com",
    cikNumber: "0000947484",
    category: "reinsurer",
    parentCompany: null,
  },
];
