export interface CarrierSeed {
  name: string;
  ticker: string | null;
  exchange: string | null;
  headquartersCountry: string;
  companyType: string;
  linesOfBusiness: string;
  isPubliclyTraded: boolean;
  description: string;
  website: string | null;
  cikNumber: string | null;
  category: string;
  parentCompany: string | null;
}

export const carriers: CarrierSeed[] = [
  // ──────────────────────────────────────────────
  // US P&C Carriers
  // ──────────────────────────────────────────────
  {
    name: "Chubb Limited",
    ticker: "CB",
    exchange: "NYSE",
    headquartersCountry: "Switzerland",
    companyType: "primary_carrier",
    linesOfBusiness: JSON.stringify(["Commercial P&C", "Personal Lines", "Specialty", "Reinsurance", "Life"]),
    isPubliclyTraded: true,
    description: "World's largest publicly traded P&C insurer. Operates in 54 countries with a diversified portfolio spanning commercial, personal, specialty, and reinsurance lines.",
    website: "https://www.chubb.com",
    cikNumber: "0000896159",
    category: "us_pc",
    parentCompany: null,
  },
  {
    name: "American International Group (AIG)",
    ticker: "AIG",
    exchange: "NYSE",
    headquartersCountry: "United States",
    companyType: "primary_carrier",
    linesOfBusiness: JSON.stringify(["Commercial Lines", "Personal Insurance", "General Insurance", "Life & Retirement"]),
    isPubliclyTraded: true,
    description: "Global insurance organization providing commercial and personal insurance solutions. Recently spun off life & retirement business as Corebridge Financial.",
    website: "https://www.aig.com",
    cikNumber: "0000005272",
    category: "us_pc",
    parentCompany: null,
  },
  {
    name: "Travelers Companies",
    ticker: "TRV",
    exchange: "NYSE",
    headquartersCountry: "United States",
    companyType: "primary_carrier",
    linesOfBusiness: JSON.stringify(["Business Insurance", "Bond & Specialty Insurance", "Personal Insurance"]),
    isPubliclyTraded: true,
    description: "Leading US P&C insurer and Dow Jones Industrial Average component. Strong in commercial lines, workers' comp, and personal auto/homeowners.",
    website: "https://www.travelers.com",
    cikNumber: "0000086312",
    category: "us_pc",
    parentCompany: null,
  },
  {
    name: "The Hartford Financial Services",
    ticker: "HIG",
    exchange: "NYSE",
    headquartersCountry: "United States",
    companyType: "primary_carrier",
    linesOfBusiness: JSON.stringify(["Commercial Lines", "Personal Lines", "Group Benefits", "Hartford Funds"]),
    isPubliclyTraded: true,
    description: "Major US insurer focused on small and mid-size commercial lines, personal auto, homeowners, and group disability/life benefits.",
    website: "https://www.thehartford.com",
    cikNumber: "0000874766",
    category: "us_pc",
    parentCompany: null,
  },
  {
    name: "Markel Group",
    ticker: "MKL",
    exchange: "NYSE",
    headquartersCountry: "United States",
    companyType: "primary_carrier",
    linesOfBusiness: JSON.stringify(["Specialty Insurance", "E&S Lines", "Reinsurance", "Markel Ventures"]),
    isPubliclyTraded: true,
    description: "Diversified financial holding company focused on specialty insurance and E&S markets. Often compared to Berkshire Hathaway for its insurance + investment model.",
    website: "https://www.markel.com",
    cikNumber: "0000070858",
    category: "us_pc",
    parentCompany: null,
  },
  {
    name: "W.R. Berkley Corporation",
    ticker: "WRB",
    exchange: "NYSE",
    headquartersCountry: "United States",
    companyType: "primary_carrier",
    linesOfBusiness: JSON.stringify(["Commercial Lines", "Specialty Lines", "Reinsurance", "International"]),
    isPubliclyTraded: true,
    description: "Decentralized specialty commercial lines insurer operating through 50+ companies. Known for underwriting discipline and niche market expertise.",
    website: "https://www.berkley.com",
    cikNumber: "0000011544",
    category: "us_pc",
    parentCompany: null,
  },
  {
    name: "CNA Financial Corporation",
    ticker: "CNA",
    exchange: "NYSE",
    headquartersCountry: "United States",
    companyType: "primary_carrier",
    linesOfBusiness: JSON.stringify(["Commercial", "Specialty", "International", "Surety"]),
    isPubliclyTraded: true,
    description: "One of the largest US commercial property and casualty companies. Majority-owned by Loews Corporation. Strong in professional liability and management liability.",
    website: "https://www.cna.com",
    cikNumber: "0000021175",
    category: "us_pc",
    parentCompany: "Loews Corporation",
  },
  {
    name: "Hanover Insurance Group",
    ticker: "THG",
    exchange: "NYSE",
    headquartersCountry: "United States",
    companyType: "primary_carrier",
    linesOfBusiness: JSON.stringify(["Commercial Lines", "Personal Lines", "Specialty"]),
    isPubliclyTraded: true,
    description: "Regional P&C insurer distributing through independent agents. Focused on small and mid-size commercial and personal lines across the US.",
    website: "https://www.hanover.com",
    cikNumber: "0000850141",
    category: "us_pc",
    parentCompany: null,
  },
  {
    name: "RLI Corp",
    ticker: "RLI",
    exchange: "NYSE",
    headquartersCountry: "United States",
    companyType: "primary_carrier",
    linesOfBusiness: JSON.stringify(["Casualty", "Property", "Surety"]),
    isPubliclyTraded: true,
    description: "Specialty insurer with exceptional underwriting track record. Focuses on niche casualty, property, and surety markets with consistently low combined ratios.",
    website: "https://www.rlicorp.com",
    cikNumber: "0000730464",
    category: "us_pc",
    parentCompany: null,
  },
  {
    name: "Cincinnati Financial Corporation",
    ticker: "CINF",
    exchange: "NASDAQ",
    headquartersCountry: "United States",
    companyType: "primary_carrier",
    linesOfBusiness: JSON.stringify(["Commercial Lines", "Personal Lines", "Excess & Surplus", "Life Insurance"]),
    isPubliclyTraded: true,
    description: "Independent agency-focused P&C insurer known for long-term agent relationships and consistent dividend growth. Operates primarily in the Midwest and Southeast.",
    website: "https://www.cinfin.com",
    cikNumber: "0000020286",
    category: "us_pc",
    parentCompany: null,
  },
  {
    name: "Erie Indemnity Company",
    ticker: "ERIE",
    exchange: "NASDAQ",
    headquartersCountry: "United States",
    companyType: "primary_carrier",
    linesOfBusiness: JSON.stringify(["Personal Auto", "Homeowners", "Commercial Multi-Peril", "Workers Comp"]),
    isPubliclyTraded: true,
    description: "Management company for the Erie Insurance Exchange. Top-rated for customer satisfaction in personal auto and homeowners. Operates in 12 mid-Atlantic and Midwest states.",
    website: "https://www.erieinsurance.com",
    cikNumber: "0000049697",
    category: "us_pc",
    parentCompany: null,
  },
  {
    name: "Auto-Owners Insurance Group",
    ticker: null,
    exchange: null,
    headquartersCountry: "United States",
    companyType: "mutual",
    linesOfBusiness: JSON.stringify(["Personal Auto", "Homeowners", "Commercial Lines", "Life Insurance", "Auto Dealership Programs"]),
    isPubliclyTraded: false,
    description: "Large mutual insurer operating in 26 states through independent agents. Strong in personal lines and commercial auto, including auto dealership programs.",
    website: "https://www.auto-owners.com",
    cikNumber: null,
    category: "us_pc",
    parentCompany: null,
  },
  {
    name: "Nationwide Mutual Insurance",
    ticker: null,
    exchange: null,
    headquartersCountry: "United States",
    companyType: "mutual",
    linesOfBusiness: JSON.stringify(["Personal Auto", "Homeowners", "Commercial Lines", "Financial Services", "Pet Insurance"]),
    isPubliclyTraded: false,
    description: "One of the largest US insurance and financial services companies. Fortune 100 mutual insurer with diversified operations across P&C, life, and financial services.",
    website: "https://www.nationwide.com",
    cikNumber: null,
    category: "us_pc",
    parentCompany: null,
  },
  {
    name: "Liberty Mutual Insurance",
    ticker: null,
    exchange: null,
    headquartersCountry: "United States",
    companyType: "mutual",
    linesOfBusiness: JSON.stringify(["Personal Auto", "Homeowners", "Commercial Lines", "Global Specialty", "Reinsurance"]),
    isPubliclyTraded: false,
    description: "Sixth-largest P&C insurer globally. Diversified mutual with operations in personal lines, commercial insurance, and global reinsurance (GRM segment).",
    website: "https://www.libertymutual.com",
    cikNumber: null,
    category: "us_pc",
    parentCompany: null,
  },
  {
    name: "State Farm Mutual",
    ticker: null,
    exchange: null,
    headquartersCountry: "United States",
    companyType: "mutual",
    linesOfBusiness: JSON.stringify(["Personal Auto", "Homeowners", "Commercial Lines", "Life Insurance", "Banking"]),
    isPubliclyTraded: false,
    description: "Largest P&C insurer in the US by direct premiums written. Dominant market share in personal auto and homeowners through exclusive agent distribution.",
    website: "https://www.statefarm.com",
    cikNumber: null,
    category: "us_pc",
    parentCompany: null,
  },

  // ──────────────────────────────────────────────
  // Global Carriers with US P&C Presence
  // ──────────────────────────────────────────────
  {
    name: "Zurich Insurance Group",
    ticker: "ZURN.SW",
    exchange: "SIX",
    headquartersCountry: "Switzerland",
    companyType: "primary_carrier",
    linesOfBusiness: JSON.stringify(["Commercial Insurance", "Personal Lines", "Farmers Exchanges", "Life Insurance"]),
    isPubliclyTraded: true,
    description: "Global multi-line insurer with significant US presence through Zurich North America. Manages Farmers Insurance exchanges. Major player in commercial P&C and auto dealership programs.",
    website: "https://www.zurich.com",
    cikNumber: null,
    category: "global",
    parentCompany: null,
  },
  {
    name: "Allianz SE",
    ticker: "ALV.DE",
    exchange: "XETRA",
    headquartersCountry: "Germany",
    companyType: "primary_carrier",
    linesOfBusiness: JSON.stringify(["P&C Insurance", "Life/Health", "Asset Management", "Specialty Lines"]),
    isPubliclyTraded: true,
    description: "World's largest insurance company by revenue. US presence through Allianz Life, Fireman's Fund (run-off), and PIMCO asset management.",
    website: "https://www.allianz.com",
    cikNumber: null,
    category: "global",
    parentCompany: null,
  },
  {
    name: "AXA SA",
    ticker: "CS.PA",
    exchange: "Euronext Paris",
    headquartersCountry: "France",
    companyType: "primary_carrier",
    linesOfBusiness: JSON.stringify(["P&C Insurance", "Life & Savings", "Health Insurance", "Asset Management"]),
    isPubliclyTraded: true,
    description: "Global insurance leader with US presence through AXA XL (commercial P&C and specialty). One of the largest commercial lines and specialty insurers globally.",
    website: "https://www.axa.com",
    cikNumber: null,
    category: "global",
    parentCompany: null,
  },
  {
    name: "Lloyd's of London",
    ticker: null,
    exchange: null,
    headquartersCountry: "United Kingdom",
    companyType: "market",
    linesOfBusiness: JSON.stringify(["Specialty Insurance", "Reinsurance", "Marine", "Aviation", "Cyber", "Political Risk"]),
    isPubliclyTraded: false,
    description: "World's leading insurance and reinsurance marketplace. Not a single company but a market of 50+ syndicates. Dominant in specialty and hard-to-place risks globally.",
    website: "https://www.lloyds.com",
    cikNumber: null,
    category: "global",
    parentCompany: null,
  },
  {
    name: "Fairfax Financial Holdings",
    ticker: "FFH.TO",
    exchange: "TSX",
    headquartersCountry: "Canada",
    companyType: "primary_carrier",
    linesOfBusiness: JSON.stringify(["Insurance", "Reinsurance", "Investment Management", "Run-off"]),
    isPubliclyTraded: true,
    description: "Canadian insurance holding company modeled after Berkshire Hathaway. Owns multiple US-based insurers including Zenith National, Crum & Forster, and Odyssey Group.",
    website: "https://www.fairfax.ca",
    cikNumber: null,
    category: "global",
    parentCompany: null,
  },
  {
    name: "Intact Financial Corporation",
    ticker: "IFC.TO",
    exchange: "TSX",
    headquartersCountry: "Canada",
    companyType: "primary_carrier",
    linesOfBusiness: JSON.stringify(["Personal Auto", "Personal Property", "Commercial Lines", "Specialty Lines"]),
    isPubliclyTraded: true,
    description: "Largest P&C insurer in Canada. Expanded US and UK specialty presence through acquisition of RSA Insurance Group. Growing US specialty operation.",
    website: "https://www.intactfc.com",
    cikNumber: null,
    category: "global",
    parentCompany: null,
  },
  {
    name: "QBE Insurance Group",
    ticker: "QBE.AX",
    exchange: "ASX",
    headquartersCountry: "Australia",
    companyType: "primary_carrier",
    linesOfBusiness: JSON.stringify(["Commercial Lines", "Specialty", "Crop Insurance", "Personal Lines"]),
    isPubliclyTraded: true,
    description: "Australian-based global insurer with significant US operations through QBE North America. Strong in commercial lines, crop insurance, and specialty programs.",
    website: "https://www.qbe.com",
    cikNumber: null,
    category: "global",
    parentCompany: null,
  },
  {
    name: "Tokio Marine Holdings",
    ticker: "8766.T",
    exchange: "TSE",
    headquartersCountry: "Japan",
    companyType: "primary_carrier",
    linesOfBusiness: JSON.stringify(["Domestic P&C", "International Insurance", "Life Insurance", "Specialty"]),
    isPubliclyTraded: true,
    description: "Japan's largest P&C insurer with growing international presence. US operations include Philadelphia Insurance (PHLY), Delphi Financial, and HCC Insurance Holdings.",
    website: "https://www.tokiomarinehd.com",
    cikNumber: null,
    category: "global",
    parentCompany: null,
  },
  {
    name: "Sompo Holdings",
    ticker: "8630.T",
    exchange: "TSE",
    headquartersCountry: "Japan",
    companyType: "primary_carrier",
    linesOfBusiness: JSON.stringify(["Domestic P&C", "International Insurance", "Life Insurance", "Nursing Care"]),
    isPubliclyTraded: true,
    description: "Major Japanese insurer with US presence through Sompo International (formerly Endurance Specialty). Growing commercial and specialty lines platform in North America.",
    website: "https://www.sompo-hd.com",
    cikNumber: null,
    category: "global",
    parentCompany: null,
  },

  // ──────────────────────────────────────────────
  // Reinsurers
  // ──────────────────────────────────────────────
  {
    name: "Swiss Re AG",
    ticker: "SREN.SW",
    exchange: "SIX",
    headquartersCountry: "Switzerland",
    companyType: "reinsurer",
    linesOfBusiness: JSON.stringify(["P&C Reinsurance", "Life & Health Reinsurance", "Corporate Solutions"]),
    isPubliclyTraded: true,
    description: "World's second-largest reinsurer. Key market cycle indicator — their commentary on pricing, capacity, and cat losses shapes the global insurance market.",
    website: "https://www.swissre.com",
    cikNumber: null,
    category: "reinsurer",
    parentCompany: null,
  },
  {
    name: "Munich Re (Münchener Rück)",
    ticker: "MUV2.DE",
    exchange: "XETRA",
    headquartersCountry: "Germany",
    companyType: "reinsurer",
    linesOfBusiness: JSON.stringify(["P&C Reinsurance", "Life Reinsurance", "ERGO (Primary)", "Specialty"]),
    isPubliclyTraded: true,
    description: "World's largest reinsurer. Sets the tone for global reinsurance pricing at January 1 renewals. Also operates primary insurer ERGO and Munich Re Specialty Group.",
    website: "https://www.munichre.com",
    cikNumber: null,
    category: "reinsurer",
    parentCompany: null,
  },
  {
    name: "Hannover Rück SE",
    ticker: "HNR1.DE",
    exchange: "XETRA",
    headquartersCountry: "Germany",
    companyType: "reinsurer",
    linesOfBusiness: JSON.stringify(["P&C Reinsurance", "Life & Health Reinsurance"]),
    isPubliclyTraded: true,
    description: "World's third-largest reinsurer. Known for conservative underwriting and strong technical expertise. Majority-owned by Talanx AG/HDI Group.",
    website: "https://www.hannover-re.com",
    cikNumber: null,
    category: "reinsurer",
    parentCompany: "Talanx AG",
  },
  {
    name: "General Reinsurance (Gen Re)",
    ticker: null,
    exchange: null,
    headquartersCountry: "United States",
    companyType: "reinsurer",
    linesOfBusiness: JSON.stringify(["P&C Reinsurance", "Life Reinsurance"]),
    isPubliclyTraded: false,
    description: "Premier US reinsurer and Berkshire Hathaway subsidiary. One of the highest-rated reinsurers globally. Known for conservative, long-term approach to reinsurance.",
    website: "https://www.genre.com",
    cikNumber: null,
    category: "reinsurer",
    parentCompany: "Berkshire Hathaway",
  },
  {
    name: "Everest Group",
    ticker: "EG",
    exchange: "NYSE",
    headquartersCountry: "Bermuda",
    companyType: "reinsurer",
    linesOfBusiness: JSON.stringify(["P&C Reinsurance", "Insurance", "Specialty"]),
    isPubliclyTraded: true,
    description: "Leading global reinsurer and insurer operating through Everest Re and Everest Insurance. Active across treaty, facultative, and specialty lines.",
    website: "https://www.everestglobal.com",
    cikNumber: "0000819544",
    category: "reinsurer",
    parentCompany: null,
  },
  {
    name: "RenaissanceRe Holdings",
    ticker: "RNR",
    exchange: "NYSE",
    headquartersCountry: "Bermuda",
    companyType: "reinsurer",
    linesOfBusiness: JSON.stringify(["Property Cat Reinsurance", "Casualty Reinsurance", "Specialty Reinsurance"]),
    isPubliclyTraded: true,
    description: "Leading property catastrophe reinsurer known for sophisticated risk modeling and disciplined cycle management. Expanded casualty book significantly in recent years.",
    website: "https://www.renre.com",
    cikNumber: "0000913144",
    category: "reinsurer",
    parentCompany: null,
  },
  {
    name: "Arch Capital Group",
    ticker: "ACGL",
    exchange: "NASDAQ",
    headquartersCountry: "Bermuda",
    companyType: "reinsurer",
    linesOfBusiness: JSON.stringify(["Reinsurance", "Insurance", "Mortgage Insurance"]),
    isPubliclyTraded: true,
    description: "Bermuda-based insurer/reinsurer with strong track record. Operates across reinsurance, insurance, and mortgage guarantee segments. Known for disciplined underwriting.",
    website: "https://www.archgroup.com",
    cikNumber: "0001121796",
    category: "reinsurer",
    parentCompany: null,
  },
  {
    name: "TransAtlantic Reinsurance (TransRe)",
    ticker: null,
    exchange: null,
    headquartersCountry: "United States",
    companyType: "reinsurer",
    linesOfBusiness: JSON.stringify(["P&C Reinsurance", "Specialty Reinsurance"]),
    isPubliclyTraded: false,
    description: "Major US reinsurer, formerly part of Alleghany Corporation, now a Berkshire Hathaway subsidiary. Active across property, casualty, and specialty treaty reinsurance.",
    website: "https://www.transre.com",
    cikNumber: null,
    category: "reinsurer",
    parentCompany: "Berkshire Hathaway",
  },
  {
    name: "SCOR SE",
    ticker: "SCR.PA",
    exchange: "Euronext Paris",
    headquartersCountry: "France",
    companyType: "reinsurer",
    linesOfBusiness: JSON.stringify(["P&C Reinsurance", "Life Reinsurance", "Specialty"]),
    isPubliclyTraded: true,
    description: "Global reinsurer with strong positions in life and P&C reinsurance. Being acquired by Covéa. Known for technical expertise and Tier 1 capital strength.",
    website: "https://www.scor.com",
    cikNumber: null,
    category: "reinsurer",
    parentCompany: null,
  },
  {
    name: "PartnerRe",
    ticker: null,
    exchange: null,
    headquartersCountry: "Bermuda",
    companyType: "reinsurer",
    linesOfBusiness: JSON.stringify(["P&C Reinsurance", "Life Reinsurance", "Specialty"]),
    isPubliclyTraded: false,
    description: "Global reinsurer now owned by French mutual insurer Covéa. Diversified book across property, casualty, specialty, and life/health reinsurance.",
    website: "https://www.partnerre.com",
    cikNumber: null,
    category: "reinsurer",
    parentCompany: "Covéa",
  },

  // ──────────────────────────────────────────────
  // Auto Dealership Niche Players
  // ──────────────────────────────────────────────
  {
    name: "Ally Financial / Motors Insurance Corp",
    ticker: "ALLY",
    exchange: "NYSE",
    headquartersCountry: "United States",
    companyType: "primary_carrier",
    linesOfBusiness: JSON.stringify(["Dealer Financial Products", "Vehicle Service Contracts", "GAP Insurance", "Commercial Auto"]),
    isPubliclyTraded: true,
    description: "Leading auto finance company with insurance operations through Motors Insurance Corp. Provides dealer-centric financial products including F&I, VSCs, and GAP coverage.",
    website: "https://www.ally.com",
    cikNumber: "0000040730",
    category: "auto_dealer_niche",
    parentCompany: null,
  },
  {
    name: "Zurich North America (Dealership Programs)",
    ticker: null,
    exchange: null,
    headquartersCountry: "United States",
    companyType: "primary_carrier",
    linesOfBusiness: JSON.stringify(["Dealer Open Lot", "Garage Liability", "Commercial Auto", "Workers Comp", "Umbrella"]),
    isPubliclyTraded: false,
    description: "Major auto dealership insurance program through Zurich North America. One of the largest providers of dealer open lot, garage liability, and commercial auto for dealerships.",
    website: "https://www.zurichna.com",
    cikNumber: null,
    category: "auto_dealer_niche",
    parentCompany: "Zurich Insurance Group",
  },
  {
    name: "Risk Point / Ategrity Specialty",
    ticker: null,
    exchange: null,
    headquartersCountry: "United States",
    companyType: "mga_specialty",
    linesOfBusiness: JSON.stringify(["Dealer Open Lot", "Garage Liability", "F&I Products", "Dealer E&O"]),
    isPubliclyTraded: false,
    description: "Specialty MGA focused exclusively on the auto dealership vertical. Provides tailored open lot, garage liability, and dealer E&O programs.",
    website: null,
    cikNumber: null,
    category: "auto_dealer_niche",
    parentCompany: null,
  },
  {
    name: "Alliant Insurance Services",
    ticker: null,
    exchange: null,
    headquartersCountry: "United States",
    companyType: "broker",
    linesOfBusiness: JSON.stringify(["Dealer Programs", "Commercial P&C", "Employee Benefits", "Specialty"]),
    isPubliclyTraded: false,
    description: "Major insurance brokerage with a dedicated auto dealership practice group. Provides comprehensive insurance and risk management programs for dealers nationwide.",
    website: "https://www.alliant.com",
    cikNumber: null,
    category: "auto_dealer_niche",
    parentCompany: null,
  },
  {
    name: "Sentry Insurance Group",
    ticker: null,
    exchange: null,
    headquartersCountry: "United States",
    companyType: "mutual",
    linesOfBusiness: JSON.stringify(["Commercial Auto", "Workers Comp", "Property", "General Liability", "Dealer Programs"]),
    isPubliclyTraded: false,
    description: "Wisconsin-based mutual insurer with dedicated auto dealership insurance programs. Provides commercial auto, workers comp, and property coverage for dealers.",
    website: "https://www.sentry.com",
    cikNumber: null,
    category: "auto_dealer_niche",
    parentCompany: null,
  },
  {
    name: "Federated Insurance",
    ticker: null,
    exchange: null,
    headquartersCountry: "United States",
    companyType: "mutual",
    linesOfBusiness: JSON.stringify(["Commercial Auto", "Property", "General Liability", "Workers Comp", "Dealer Programs"]),
    isPubliclyTraded: false,
    description: "Owatonna, MN-based mutual insurer specializing in niche commercial markets including auto dealerships. Known for direct field marketing representatives.",
    website: "https://www.federatedinsurance.com",
    cikNumber: null,
    category: "auto_dealer_niche",
    parentCompany: null,
  },
  {
    name: "Protective Insurance (Kemper)",
    ticker: null,
    exchange: null,
    headquartersCountry: "United States",
    companyType: "primary_carrier",
    linesOfBusiness: JSON.stringify(["Commercial Auto", "General Liability", "Physical Damage", "Workers Comp"]),
    isPubliclyTraded: false,
    description: "Subsidiary of Kemper Corporation focused on specialty commercial auto and fleet insurance. Relevant to auto dealership operations and dealer fleet programs.",
    website: "https://www.kemper.com",
    cikNumber: null,
    category: "auto_dealer_niche",
    parentCompany: "Kemper Corporation",
  },
];
